### ISSUE TITLE
Data Missed

### ISSUE THREAD

**Issue by PJJFMarques** [Curbal-Data-Labs/Matplotlib-Labs#1]
Hi Ruth,
Several of the labs are without the data available... can you provide them?

**Comment by ruthpozuelo** [comment]
Hi @PJJFMarques , all the datasets are Makeover Mondays data. 
You can see which year and week on the file name.

Example, for this dataset:
dataset = pd.read_csv(r'C:\Users\Ruth Pozuelo\Documents\python_examples\data\2018w6.csv'

The makeover monday is year 2018 week 6. 
Is that enough?

**Comment by PJJFMarques** [comment]
Thanks Ruth for the clue...
