### ISSUE TITLE
Bar chart small multiples.ipynb

### ISSUE THREAD

**Issue by dewic** [Curbal-Data-Labs/Matplotlib-Labs#3]
HI, I am unable to replicate chart ***Bar chart small multiples***. Can you clarify where are the color_list and color_list1 variables defined?
```python
...
for value, color in zip(ax1.patches,color_list1):
...
for value, color in zip(ax3.patches,color_list):
```
Thank you for your help.

**Comment by ruthpozuelo** [comment]
Hi @dewic ,
Yes, that is wrong.
I haven't been able to pass a list to an ax.text color property, so maybe it is not possible.
I re-uploaded the file with the correct code where I filter the data frame by the column "ownership" so only those data labels are displayed and then I used color= black.

Hope this works for you and if it does, can you then close the comment? Thanks!
